version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10
  logzio-orb: logzio/logzio-orb@1.0.1
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - release:
          type: approval
          requires:
            - build-and-test
      - heroku/deploy-via-git:
          requires:
            - release
jobs:
  build-and-test:
    docker:
      - image: logzio/docker-collector-metrics
        environment:
          LOGZIO_TOKEN: ${LOGZIO_METRICS_TOKEN}
          LOGZIO_MODULES: docker
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: mkdir -p ~/reports
            - run: mkdir -p ~/logs
            - run: npm install
            - run:
                name: Run linter
                command: npm run lint:ci
            - run:
                name: Run unit tests with JUnit as reporter
                command: npm run unit:ci
                environment:
                  JEST_JUNIT_OUTPUT_DIR: ~/reports
            - store_test_results:
                path: ~/reports
            - store_artifacts:
                path: ~/reports
            - store_artifacts:
                path:  ~/project/coverage/lcov-report
                destination: coverage
      - logzio-orb/submit:
          dir-path: ~/logs