version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - release:
          type: approval
          requires:
            - build-and-test
      - heroku/deploy-via-git:
          requires:
            - release
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test