version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  # logzio-orb: logzio/logzio-orb@1.0.1
jobs:
  build-and-test:
    docker:
      # - image: circleci/node:12
      - image: logzio/docker-collector-metrics
        environment:
          LOGZIO_TOKEN: ${LOGZIO_METRICS_TOKEN}
          LOGZIO_MODULES: docker
    steps:
      - run:
          name: Install Git
          command: |
            apt update
            apt install -y git
      - run:
          name: Install node
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | bash -
            apt-get install -y nodejs
            npm i -g npm
            node --version
            npm --version
      - checkout
      - run:
          name: NPM install
          command: npm install
      - run:
          name: Run linter
          command: npm run lint:ci
      - run:
          name: Run unit tests with JUnit as reporter
          command: npm run unit:ci
      - run:
          name: Be brutal to the memory
          command: npm build && node -e "require('~/dist/memory-hog.js')(100000);"
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - release:
          type: approval
          requires:
            - build-and-test
      - heroku/deploy-via-git:
          requires:
            - release